version: '3'
services:
  postgres:
    image: postgres:15.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acadnet
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data